spring:
  http:
    multipart:
      max-file-size: 100Mb 
      max-request-size: 100Mb
  application:
    name: courseware-service
  datasource:
    tomcat:
       min-idle: 3
       max-idle: 5
       max-active: 5
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.18.30.100:1521/orcl
    username: CONSULTATION
    password: CONSULTATION
  redis:
    host: localhost
    port: 6379
    database: 0
    password: medical
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000

mybatis:
  mapper-locations: classpath*:sqlmapper/*Mapper.xml
  type-aliases-package: com.medical.courseware.domain
 
server:
  port: 5002
  max-http-header-size: 10000000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5111/eureka/
  
quartz:
  quartzConfigJobName: "medical-courseware-numOfHit"
  quartzConfigJobGroup: "medical-courseware"
  targetMethod: "executeInternal"
  cronExpression: "0 0 13,23 * * ?"
  tiggerName: "medical-courseware-numOfHit"  