eureka:
  client:
    service-url:
      defaultZone: http://localhost:5111/eureka/
server:
  port: 5005
  max-http-header-size: 4048576
  servlet:
    path: /

spring:
  http:
    multipart:
      max-file-size: 10Mb 
      max-request-size: 10mb
  application:
    name: telemedicine-service
  datasource:
    tomcat:
        min-idle: 3
        max-idle: 5
        max-active: 5
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.247.2:1521/orcl
    username: CONSULTATION
    password: CONSULTATION
  redis:
    host: localhost
    port: 6379
    database: 0
#    password: medical
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
 
mybatis:
  type-aliases-package: com.medical.telemedicine.domain
  mapper-locations: classpath*:sqlmapper/*Mapper.xml

spring.jackson.time-zone: GMT+8

assist-dispose:
  auxiliary-diagnosis:
    url: 'http://172.18.30.118:8000/teleai/getAuxiliaryDiagnosis'
  consultation-from-txt:
    url: 'http://172.18.30.118:8000/teleai/consultationFromTxt'

consulatation:
  file:
    path: x:\\teleai

